spring:
  application:
    name: netapi
  datasource:
    url: jdbc:mysql://localhost:3306/teamsheets?autoReconnect=true&useSSL=false
    username: aosborn
    password: Osbo_789101112
  jpa:
    hibernate:
      ddl-auto: none
    Show-sql: false